/*
Cliente reproduz tudo e exibe na tela (engine do jogo)
* Recebe informações do servidor e mostra na tela
* Envia comandos de ações dentro do jogo
* Protocolo de comunicação: Nome
 */
package client;

import java.awt.event.KeyEvent;
import java.io.IOException;
import server.Maze;

public class Client extends javax.swing.JFrame {

    TCPCommunication tcpCom;
    String targetIP;
    Maze maze;
    String response;
    Player player;

    public Client() {
        initComponents();
        MainPnl.setFocusable(true);
        MainPnl.requestFocus();
        targetIP = "192.168.0.9";
        this.tcpCom = new TCPCommunication(targetIP);
        this.maze = new Maze(); // já roda a Thread da classe Maze
        response = ""; //variável para receber a resposta do servidor
        pnlControls.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfdPlayer = new javax.swing.JTextField();
        pnlControls = new javax.swing.JPanel();
        btnW = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnAtirar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPnl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MainPnlKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome do jogador: ");

        btnW.setText("W");
        btnW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWActionPerformed(evt);
            }
        });

        btnS.setText("S");
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });

        btnA.setText("A");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnD.setText("D");
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });

        btnAtirar.setText("ATIRAR! (X)");
        btnAtirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlsLayout = new javax.swing.GroupLayout(pnlControls);
        pnlControls.setLayout(pnlControlsLayout);
        pnlControlsLayout.setHorizontalGroup(
            pnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(pnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnW, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlControlsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(btnAtirar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        pnlControlsLayout.setVerticalGroup(
            pnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlsLayout.createSequentialGroup()
                .addGroup(pnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlControlsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnW, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlControlsLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtirar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlControlsLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnIniciar.setText("INICIAR JOGO");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPnlLayout = new javax.swing.GroupLayout(MainPnl);
        MainPnl.setLayout(MainPnlLayout);
        MainPnlLayout.setHorizontalGroup(
            MainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPnlLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .addComponent(tfdPlayer)))
                    .addComponent(pnlControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPnlLayout.setVerticalGroup(
            MainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPnlLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(MainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(pnlControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWActionPerformed
        try {
            response = tcpCom.sendCommand(this.player.getName() + "-" + "W");
            handleResponse(response);
        } catch (IOException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnWActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        try {
            response = tcpCom.sendCommand(this.player.getName() + "-" + "A");
            handleResponse(response);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        try {
            response = tcpCom.sendCommand(this.player.getName() + "-" + "S");
            handleResponse(response);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        try {
            response = tcpCom.sendCommand(this.player.getName() + "-" + "D");
            handleResponse(response);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDActionPerformed

    private void MainPnlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MainPnlKeyReleased

        try {
            if (evt.getKeyCode() == KeyEvent.VK_W) {
                response = tcpCom.sendCommand(this.player.getName() + "-" +  "W");
                handleResponse(response);
            } else if (evt.getKeyCode() == KeyEvent.VK_A) {
                response = tcpCom.sendCommand(this.player.getName() + "-" + "A");
                handleResponse(response);
            } else if (evt.getKeyCode() == KeyEvent.VK_S) {
                response = tcpCom.sendCommand(this.player.getName() + "-" + "S");
                handleResponse(response);
            } else if (evt.getKeyCode() == KeyEvent.VK_D) {
                response = tcpCom.sendCommand(this.player.getName() + "-" + "D");
                handleResponse(response);
            } else if (evt.getKeyCode() == KeyEvent.VK_X) { // Atirar!
                response = tcpCom.sendCommand(this.player.getName() + "-" + "X");
                handleResponse(response);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_MainPnlKeyReleased

    private void btnAtirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtirarActionPerformed
        try {
            response = tcpCom.sendCommand(this.player.getName() + "-" + "X");
            handleResponse(response);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAtirarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        if (tfdPlayer.getText().length() == 0) {
           this.player = new Player("Desconhecido:" + (int) (Math.random() * 30));
           tfdPlayer.setText(this.player.getName());
        } else {
           this.player = new Player(tfdPlayer.getText()); 
        }
         
        System.out.println(this.player.getName() + " entrou no jogo...");
        pnlControls.setVisible(true);
        this.btnIniciar.setEnabled(false);
        this.tfdPlayer.setEnabled(false);
        
        //Enviar pro server o nome do jogador pra ele adicionar ao game
        try {
            response = tcpCom.sendCommand(this.player.getName() + "-" + "L");
        } catch (IOException e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void handleResponse(String response) {
        //Servidor irá enviar a posição do jogador de volta para ser setado no lab
        //Servidor será apenas um "atualizador" que envia as posições pros outros jogadores
        // o disparo pode ser "atrasado" usando Thread.sleep(2000);
        // Exibe novamente na tela o labirinto do game
        this.maze.printMaze();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        // Player configuration
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPnl;
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnAtirar;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnW;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlControls;
    private javax.swing.JTextField tfdPlayer;
    // End of variables declaration//GEN-END:variables
}
